"""Initial migration.

Revision ID: 60afcc5e0468
Revises: c02bb812d26d
Create Date: 2024-11-11 14:36:44.633312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60afcc5e0468'
down_revision = 'c02bb812d26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
