"""user role added

Revision ID: 95376bfba14a
Revises: 19bb31fa750c
Create Date: 2024-11-11 16:21:21.764025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95376bfba14a'
down_revision = '19bb31fa750c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
